### ISSUE TITLE
Retravailler la méca de la base roulante de Céres

### ISSUE THREAD

**Issue by astralien3000** [xenomorphales/xenomorphales#10]
Avec de nouveaux blocs moteurs (avec le renvoi d'angle), et de nouveaux encodeurs, il faudra sûrement retravailler la base roulante de Céres.
Donc déjà, il faut que je mette en ligne les anciens fichiers Autodesk Inventor, dans un endroit où on pourra les modifier. J'hésite à les mettre sur github, parceque ces fichiers sont lourds.

**Comment by Elioty** [comment]
On peut fermer cette issue en faveur de la #17, n'est-ce pas ?

**Comment by astralien3000** [comment]
En effet... C'est un peu le bazar dans les issues quand même ><
