### ISSUE TITLE
Innorobo 2015

### ISSUE THREAD

**Issue by astralien3000** [xenomorphales/xenomorphales#20]
Il y a le forum innorobo 2015 qui se déroule à Lyon le vendredi 3 juillet.
On pourra y rencontrer Optoforce, le futur sponsor de buggybot.
Et on pourrai peut être trouver d'autres sponsors ?

Enfin bon, voila. Vu que tu es pas trop loin Nico, ça peut t'intéresser ?
Clément, si je me rappelles bien, ça peut t'intéresser aussi ?

Voila, qu'en dites-vous ?

**Comment by nbelin** [comment]
Heu oui ça a l'air intéressant, on peut peut-être même y amener son CV ;)
Par contre c'est dans la journée ? Vu que j'ai 1h30 de trajet pour aller à Lyon depuis mon boulot, faut que je prenne l'aprem voire la journée entière...
On peut en discuter si vous voulez, j'ai peut-être pas tout compris :)

**Comment by astralien3000** [comment]
C'est de 9h à 17h ascii paraît.
[les info](http://innorobo.com/practical-infos/)

Faudra sûrement prendre la journée pour y aller. En tout cas pour nous c'est réglé si on y va.
En tou cas j'ai vu certains participants, et rien que pour les voir, je trouve que ça vaut la peine.

**Comment by nbelin** [comment]
Écoute j'ai pas de jours de congés sur ma convention du coup je demanderai mais je ne peux pas promettre d'avoir la possibilité d'y aller. Ensuite en fonction de si vous y allez ou pas, et des participants, je verrai si j'y vais ou pas ^^

**Comment by astralien3000** [comment]
Ouaip, pas de problème ^^
C'est une proposition.

Mais demande quand même ça coûte rien.

**Comment by Elioty** [comment]
Je serais bien venu mais franchement, je ne sais pas si je peux avoir un jour :/
Concernant Optoforce, ils seront dans quel hall, tu sais ? Parce que le prix du ticket est différent selon le hall que tu veux visiter donc fait bien attention d'aller là où ils sont quoi !

**Comment by astralien3000** [comment]
Ils sont dans le hall d'exhibition normalement, j'ai vérifié sur la floormap. Au pire je leur demanderai quand même pour être sûr. Et normalement le prix du visiteur étudiant (ne donnant accès qu'au hall d'exhibition) est de 10€.
Par contre, c'est le déplacement qui est chiant... Le train, c'est même pas la peine si on est à 2. Ca serait plus en voiture.

**Comment by nbelin** [comment]
Bordeaux -> Lyon en train c'est effectivement pas le plus pratique :/

**Comment by Elioty** [comment]
Ouais mais en voiture, faudrait limite partir la veille ou très tôt dans la nuit :X Puis se taper la route aller/retour pour un jour, ça fait lourd quand même >_<

**Comment by astralien3000** [comment]
Ouai, bon, je sais pas si ça vaut le coup finalement. ><
J'aurai proposé...

**Comment by nbelin** [comment]
Après c'est un vendredi, je dois vérifier que je serai bien là ce weekend, mais vous pourriez dormir chez nous le soir (70m² :p)

**Comment by astralien3000** [comment]
Alors ?
Des nouvelles de ce côté ?

**Comment by nbelin** [comment]
Zut j'ai toujours pas demandé si je pouvais prendre la journée (en même temps, mon maître de stage n'a jamais de temps pour moi...). Faudrait vraiment que je me motive à me bouger le cul, mais c'est sûr que si j'ai la possibilité d'y aller et que vous y allez, j'y vais. Si j'ai la possibilité et que vous y allez pas, ça va être compliqué ^^

**Comment by astralien3000** [comment]
Donc, après de nombreuses discussions, nous allons à innorobo avec Clément en voiture !
On peut acheter les tickets d'entrée sur place ou sur le site web, il faut qu'on en discute encore un peu.
Mais je pense qu'on peut clore la discussion !

On va voir notre sponsor Optoforce ! (j'ai le contrat entre le mains) !
Et on va voir plein de trucs marrants !
