### ISSUE TITLE
Site web

### ISSUE THREAD

**Issue by astralien3000** [xenomorphales/xenomorphales#21]
Il faudrait faire un site web (simple !) pour notre communication.
En effet, si j'arrive à obtenir plusieurs sponsors, ça serait bien de les tenir informés, tout en leur faisant de la pub.
Et puis même pour nous ça serait cool d'avoir un joli site à montrer aux gens ^^ !
github.io devrait faire amplement l'affaire en tant qu'hébergement.

**Comment by Elioty** [comment]
Ouais, ça serait bien effectivement. Et je pense qu'on pourrait utiliser jekyll comme le suggère Github pour n'avoir qu'à éditer le contenu sans trop avoir à se soucier du reste.

**Comment by astralien3000** [comment]
J'ai commencé le travail !
[lien (à jour)](http://astralien3000.github.io/xenomorphales/)

Jekyll marche bien, et est bien pratique.
Une fois tout mis en place, on pourra mettre du vrai contenu.

**Comment by astralien3000** [comment]
Voila ! C'est déjà pas mal complet là !
Il faut faire un peu de contenu maintenant, quelqu'un pour m'aider ?
Déjà faudrait que vour remplissiez vos fiches de membre.
Pour le titre, vu qu'on est finalement pas d'accord pour le nom d'équipe, j'ai laissé celui de l'année passée.

**Comment by Elioty** [comment]
Cool tout ça :) Et le template que tu as trouvé rend très bien avec notre "charte graphique/chromatique". Manque plus que le nom, et à remplir (en français et en anglais d'ailleurs).

Reste à voir pour un nom de domaine tout propre une fois qu'on aura bien choisi le nom d'équipe évidemment. Doc pour paramétrer tout ce qu'il faut : https://help.github.com/articles/setting-up-a-custom-domain-with-github-pages/

**Comment by astralien3000** [comment]
En parlant d'anglais/français, il y a pas de système natif dans Jekyll qui permette de le faire proprement. Il y a un plugins, mais github le gère pas. Ils donnent la solution d'exécuter le plugins sur son ordi puis de mettre le fichier "build" de jekyll sur le site, mais ça me plaît moyen.
Il y a peut être un moyen de faire un truc avec un système de catégories (géré par jekyll).
Ou si non on met tout sur la même page mais ça fait crade...

EDIT : 
En fait,
La question est : est-ce qu'on a envie de s'embêter à tout mettre en 2 langues ?
Pour le moment, j'au un mix des deux, mais franchement tout mettre en anglais c'est lourd je trouve.

**Comment by Elioty** [comment]
Ou sinon on écrit tout en anglais dessus sans se caser la tête avec ça. Mais ça parait effectivement moyen de push le build sorti par Jekyll alors que github-pages gère Jekyll tout seul comme un grand (sauf le plugin qui nous intéresserait évidement).

Autre solution, on écrit tout en anglais, et on fait juste les news en double (anglais/français) dans deux onglets différents (on garde le "news" pour l'anglais, on en rajoute un "nouvelles" juste à côté pour les news en français), ça serait possible ?

Sinon question design/ergonomie, je pense qu'il faudrait que la page d'accueil soit les news, plus de page de bienvenu avec le logo en géant. Et à propos du logo, il faudrait le mettre à gauche du titre en haut à gauche de la page je pense.

**Comment by Elioty** [comment]
Maintenant que le nom est décidé, on peut le mettre sur le site à la place du titre et se décider pour l'extension du nom de domaine. Je propose .com histoire de rester classique (à 11.99€ la création et 13.19€ pour le renouvellement).

Sinon, en intéressant/fun il y a aussi :
- .cat (création en promo à 6€ et renouvellement à 22.79€), juste pour le fun celui là
- .band (création en promo à 7.19€ et renouvellement à 22.79€)
- .guru (création à 28.79€ et renouvellement à 31.19€)

Bon en fait, on va rester sur le .com je pense (question tarif mais aussi parce qu'il n'y en a pas de vraiment intéressant, le .bot ou .robot n'existent pas :sob:)

J'ai indiqué tous les tarifs en TTC chez OVH. On pourrait éventuellement jeter un coup d'oeil du côté de Gandi aussi.

En fait, il semblerait que le .bot existe mais il ne serait pas encore disponible à la vente, il peut être pré-commandé sur Gandi. Et j'ai du coups jeter un coup d'oeil, xenomorphales.com est à 15.05€ TTC chez Gandi.

**Comment by astralien3000** [comment]
xenomorphales.com c'est bien.
On termine de remplir le site avant de s'en occuper par contre.

**Comment by Elioty** [comment]
Oui oui, pas de problème.

**Comment by astralien3000** [comment]
Vous pouvez remplir vos fiches membres [ici](https://github.com/astralien3000/xenomorphales/tree/gh-pages/_members).
Prenez la mienne comme modèle. Mais si vous avez des suggestions/améliorations à apporter, allez-y !

**Comment by astralien3000** [comment]
Bon, le site est plutôt bien mis en route, en plus on l'a présenté à la liste Eirbot, je pense qu'on peut clore l'issue.
