### ISSUE TITLE
Protocole de communication embed/rasp

### ISSUE THREAD

**Issue by astralien3000** [xenomorphales/xenomorphales#24]
On prendra un protocole commun pour les deux robots.

**Comment by Elioty** [comment]
Je me suis affecté la tâche, je vais essayer de pondre une spec au plus vite.

EDIT : à savoir que l'implémentation d'une ou plusieurs des couches du protocole de communication réalisé seront intégrée(s) dans Aversive++.

**Comment by astralien3000** [comment]
Seul buggybot a eu un protocole cette année.
