### ISSUE TITLE
Comunication auprès de la communité Teensy

### ISSUE THREAD

**Issue by Elioty** [xenomorphales/xenomorphales#25]
Liens utiles :
https://www.pjrc.com/teensy/projects.html
https://www.hackster.io/teensy

Une fois la base roulante suffisamment développée, il serait intéressant de communiquer le projet à la communauté sur hackster.io, tout en promouvant bien l'usage d'Aversive++ au passage.

**Comment by astralien3000** [comment]
On laisse tomber.
