### ISSUE TITLE
Faire l'asserv de Céres

### ISSUE THREAD

**Issue by astralien3000** [xenomorphales/xenomorphales#27]
Pour toi Clément
Asserv en deux étape : 
- [x] Asserv des moteurs en vitesse
- [x] Asserv en angle/distance ou angle/vitesse
- [x] Bonus : Positionnement en XY

**Comment by astralien3000** [comment]
Je ne peux que conseiller d'utiliser cette base de code : 
https://github.com/AversivePlusPlus/project-2wheel-asserv

**Comment by Elioty** [comment]
Oui, c'est bien l'idée et merci beaucoup pour tout ce travail de fait déjà :)

**Comment by astralien3000** [comment]
De rien, je l'ai fait pour m'amuser ^^. D'ailleurs je continuerai sûrement à l'améliorer avec toi.
Ca me fait penser qu'on a "oublié" une tâche : les drivers pour Céres. Même si c'est un module Aversive++, c'est plus pour Xenomorphales qu'on le réalise. Et en plus elle est pas listée dans le dépôt Aversive++.

EDIT : 
Je l'ai mis en issue ici #45.

**Comment by astralien3000** [comment]
Bon, l'asserv est faite, il reste juste à la lier au hardware (kinetis).
