### ISSUE TITLE
Demande d'intégration au cluster Aquitaine Robotics

### ISSUE THREAD

**Issue by astralien3000** [xenomorphales/xenomorphales#28]
Tout est dans le titre, il faut que j'envoie un mail à Mr Lapoire

**Comment by astralien3000** [comment]
Ils demandent le site web sur leur bulletin d'adhésion, on attends d'avoir le nom de domaine opérationnel ?
De plus, j'ai aussi mis tes coordonnées, @Elioty , ça te dérange pas ?
De toute façon j'ai pas encore envoyé.

**Comment by Elioty** [comment]
Sachant que l'assos est basé chez moi, ça ne me dérange pas que ça soit mes coordonnées effectivement, cela me semble même plus pertinent.
Concernant l'adresse web, je trouve plus pertinent effectivement d'attendre d'avoir le nom de domaine.
