### ISSUE TITLE
Faire un post sur la méca de Céres sur le site web

### ISSUE THREAD

**Issue by astralien3000** [xenomorphales/xenomorphales#30]
https://www.dropbox.com/s/yokymrsmvt6uudp/2015-09-25%2019.50.09.jpg?dl=0

https://www.dropbox.com/s/6ridwhl3ztgjm32/2015-09-25%2019.49.59.jpg?dl=0

**Comment by Elioty** [comment]
On peut clore ou tu veux remplir un peu plus le post ?

**Comment by astralien3000** [comment]
Ouai j'ai ajouté un petit commentaire, parceque ça faisait un peu vide quand même...
