### ISSUE TITLE
Dépôt BigBrother

### ISSUE THREAD

**Issue by astralien3000** [xenomorphales/xenomorphales#35]
Il faut un dépôt BigBrother.
Je l'héberge ? Ou tu le fais @nbelin ?

**Comment by Elioty** [comment]
Concernant les dépôt en général, je pense qu'il devrait être tous sous la même égide. Donc dans l'état actuel des choses, toi. Mais sachant qu'administrativement parlant, on a monté une assos, on pourrait tout autant monter une organisation sur GitHub aussi pour lui donner la propriété des dépôts, non ?
