### ISSUE TITLE
Organisation Xenomorphales

### ISSUE THREAD

**Issue by astralien3000** [xenomorphales/xenomorphales#36]
On peut créer une organisation github.
C'est peut être mieux que de tout héberger sur mon compte ^^.

**Comment by Elioty** [comment]
Ha beh j'aurais dû lire cette issue avant celle du dépôt de BigBrother. Je +1 !

**Comment by astralien3000** [comment]
Done. J'ai forké le dépôt pour laisser l'ancienne url du site web (pour le moment), mais il faudra changer un peu le dépôt pour mettre la nouvelle url.
