### ISSUE TITLE
Gestion des câbles

### ISSUE THREAD

**Issue by astralien3000** [xenomorphales/xenomorphales#42]
C'est déjà le bordel dans les câbles !
Il faut penser à mettre des guides de câbles et des marqueurs (genre couleur) aux extrémités des câbles de pair avec leur connecteur correspondant.

Puis il ne reste plus qu'à faire les câbles des GP2 et des fins de courses.
Il faut également acheter un câble USB (coudé) pour la Teensy d'un cinquantaine de centimètres.

**Comment by astralien3000** [comment]
Bon, on s'en est à peu près sorti cette année.
Il y a une utilité à garder cette tâche ?

**Comment by Elioty** [comment]
Non, je pense qu'on peut la clore ;)
