### ISSUE TITLE
Drivers Teensy 3.x

### ISSUE THREAD

**Issue by astralien3000** [xenomorphales/xenomorphales#45]
Il faut faire un/des modules Aversive++ pour la Teensy.
Les fonctionnalités à gérer sont : 
- [ ] GPIO
- [ ] Timer
- [ ] PWM
- [ ] Encoder
- [ ] Communication (UART/USB ?)

**Comment by Elioty** [comment]
Les GPIO sont supportés déjà, faut juste que je pousse le tout ;)

**Comment by astralien3000** [comment]
Il n'y a plus de driver à faire, on utilisera directement le code de Kinetis. En s'arrangeant quand même pour ne pas avoir besoin de l'IDE Arduino-like.
