### ISSUE TITLE
Encodeurs

### ISSUE THREAD

**Issue by astralien3000** [xenomorphales/xenomorphales#5]
# Objectifs
- [x] Valider les encodeurs
- [x] Acheter les encodeurs

---
# Message original

Il faut de nouveaux encodeurs quadratiques pour Cérès !
Ceux que J'avais acheté coûtaient 40€, pour 512 périodes / tours (soit 2048 impultions / tours).
Mais ils sont quasiment impratiquable pour faire des roues codeuses externes. Si ils ont un contrainte mécanique sur l'axe, le cache peut se décaler par rapport aux capteurs optique, et faire qu'une partie du tour n'est pas vu.
Je les ai acheté là : 
http://www.mouser.fr/ProductDetail/Avago-Technologies/HEDS-5540A14/?qs=sGAEpiMZZMvy8cVzszrmR%252bE9KRCgbURJyLLqyTrO6yY%3d

Donc, je conseille d'acheter des encodeurs avec au moins l'axe intégré, et encore mieux, avec la roue intégrée (je pense que c'est très rare). Si on peut diminuer les emmerdes avec ça...

**Comment by Elioty** [comment]
Oui, il faut absolument de nouveaux encodeurs pour Cérès, ce n'est pas possible d'avoir des "trous" dans le comptage. Les tiens avaient 512 incrément/décrément par tour alors, c'est bien ça ? C'est à dire sur une roue imaginons de 8cm de périmètre, ça ferait une précision de 8/512 = 0.015625cm ? :astonished: 

Pour le conseil que tu donnes, je suis parfaitement d'accord, essayons tout de même d'éviter les emmerdes (et Murphy) au maximum. Je vais essayer de chercher un petit peu de mon côté.

Edit :
En restant sur Mouser, j'ai vu ceux là :
[AEDB-9140-A12 de Avago Technologies](http://www.mouser.fr/ProductDetail/Avago-Technologies/AEDB-9140-A12/?qs=sGAEpiMZZMvy8cVzszrmR%252bE9KRCgbURJRvSRjEXHLwk%3d)
[AEDB-9140-A13 de Avago Technologies](http://www.mouser.fr/ProductDetail/Avago-Technologies/AEDB-9140-A13/?qs=sGAEpiMZZMvy8cVzszrmR%252bE9KRCgbURJzHbCykoWjSU%3d)
Je n'ai pas réussi (pas cherché très longtemps non plus) à déterminer la différence entre ces produits sachant que les prix et les caractéristiques sont identiques d'après un coups d'oeil rapide.

À voir quand même à quel point le truc est solide et encaissera les mouvements du robot, voir aussi les chocs en cas d'accident contre un autre robot ou un obstacle de la table. J'émets quelques doutes.

À étudier mais le même fabriquant propose également les codeurs et les roues seuls (on doit donc les monter) et il propose trois type de roue selon le matériau avec lequel elle est faite.

**Comment by astralien3000** [comment]
Hehe, Les roues que tu vois sont pas celles qui toucheront la table ! XD
En fait ces composant sont ce qu'il y avait dans mes encodeurs.
Faut des encodeurs avec un axe et une roue en plus, pas un encodeur avec la coque en moins !

**Comment by astralien3000** [comment]
Ce genre d'encodeur me paraît pas mal : 
http://www.robotshop.com/en/remote-controlled-armored-drink-carrier-3806-500B-5-24f.html
http://www.robotshop.com/en/6mm-rotary-encoder-1024-p-r.html

Par contre, il faut faire attention à la taille...

**Comment by Elioty** [comment]
Ils m'ont l'air pas mal par contre faut faire attention à la taille oui... De l'encodeur en lui même mais aussi du diamètre de l'axe pour que ça se cale bien avec la roue fixée de l'autre côté.
Le premier, bien qu'ayant moins d'impulsion par tour, est plus court que le second mais peut surtout encaisser pas mal plus de force (d'où la différence de prix je pense). Faut faire le calcul de la précision qu'on peut avoir avec dans tous les cas selon le diamètre de la roue que l'on met dessus.

EDIT : pour les tailles, les deux on le schéma bien détaillé avec toutes les cotes sur leur datasheet respective.

**Comment by Elioty** [comment]
Ping @astralien3000 : on prend lesquels alors d'encodeurs qu'on puisse fermer l'issue (ou la taguer en "décidée mais en attente d'achat") et que je sache avec lequel traiter pour faire l'élec ? Tu as pu modéliser ceux que tu voulais et pu les faire rentrer dans la méca ?

**Comment by astralien3000** [comment]
On prend ceux là : 
http://www.robotshop.com/en/6mm-rotary-encoder-1024-p-r.html

**Comment by astralien3000** [comment]
Fait aussi !
