### ISSUE TITLE
Système d'asserv complet pour silver

### ISSUE THREAD

**Issue by astralien3000** [xenomorphales/xenomorphales#57]
- [x] Drivers moteurs
- [x] Drivers Encodeurs
- [ ] Asserv des moteurs en vitesse
- [ ] Système de sécurité des moteurs
- [ ] Odomètre
- [ ] Différentiel
- [ ] Asserv en angle
- [ ] Asserv en vitesse
- [ ] Positionnement XY

**Comment by Sokario** [comment]
Les drivers encodeurs avaient déjà été testé en condition d'environ 5 à 10 tr/s donc, ils devraient, de mon pint de vue, être opérationnel ;)

En ce qui concerne le Driver moteur, il a été réalisé ce week-end et je vous sort une petite vidéo du robot qui avance d'ici la fin de semaine :)

**Comment by astralien3000** [comment]
Plus d'actualité non plus. On réouvrira si besoin.
