### ISSUE TITLE
API de l'asserv de silver

### ISSUE THREAD

**Issue by astralien3000** [xenomorphales/xenomorphales#58]
Il faut définir les registres que l'application haut niveau pourra utiliser pour gérer l'asserv.

**Comment by Sokario** [comment]
Je suis d'accord mais les registres dépendent du design que je réalise lors de l'implémentation du bitstream sur la carte. Il faut donc que je termine tout les blocs de l'architectures avant de pouvoir te sortir les registres qui seront utilisé.

Par contre, je m'engage à ce que tu puisses à tout moment overider la boucle d'asservissement logic du FPGA. En soit en prenant le contrôle sur certaines étapes, tu auras toujours la possibilitée de récupérer les données des autres blocs qui sont indépendants.

**Comment by astralien3000** [comment]
Même sans avoir les blocs déjà codés, on peut déjà prévoir les registres qui seront au minimum accessibles, non ? Au pire, il y aura plus de registres que prévu ^^

**Comment by Sokario** [comment]
Pour le nombre de registre employés, c'est envisageable par contre je ne pourrait pas te dire exactement leur adresse.

**Comment by astralien3000** [comment]
On ne s'occupe pas des adresses pour le moment, on s'occupe juste des noms des registres ^^

**Comment by Elioty** [comment]
Et sinon l'idée final est toujours de faire un driver pour faire un device Linux (genre /dev/monFPGAdelamort) et puis de l'open (en rw) et de le mmap dans une application ? (avec certainement une bibliothèque applicative pour faire un API plus haut niveau)

**Comment by astralien3000** [comment]
Pas de changement de ce côté là, à priori.
Mais après le fait d'avoir un linux est un plus, sans être une priorité. Si il n'y a pas de Linux, on programmera en mode bare-metal. La priorité est d'avoir l'asserv.

**Comment by astralien3000** [comment]
La discussion n'est plus d'actualité, et est ouverte sur le [dépôt de silver](https://github.com/Sokario/Silver/issues/1).
