### ISSUE TITLE
Funny action 2017

### ISSUE THREAD

**Issue by astralien3000** [xenomorphales/xenomorphales#61]
Lancer des trucs...

**Comment by astralien3000** [comment]
Nouvelles idées : 
 - Lancer une langue d'alien (facile)
 - Lancer un face-hugger (difficile)

**Comment by darwikey** [comment]
Faut pas que ca soit un engin spatial ?

**Comment by astralien3000** [comment]
Ouai bon au final pour moi ça sera un cylindre.
J'ai fini et testé mon lanceur.
Tout test bon de ton côté ? Je peux fermer l'issue ?

**Comment by darwikey** [comment]
De mon coté c'est pas fini, faut encore que le branche le servo, fasse le code, et que je créer un vrai projectile.
Mais tu peux close cette issue, j'ai ma propre issue sur le repo de Ceres
