### ISSUE TITLE
Base roulante Céres 3.0

### ISSUE THREAD

**Issue by astralien3000** [xenomorphales/xenomorphales#65]
http://www.francerobotique.com/moteurs-classiques/567-moteur-m%C3%A9tal-plan%C3%A9taire-premium-hd-12v-612rpm-avec-encodeur.html

**Comment by Elioty** [comment]
Ah ouais, ce n'est pas le même prix que les moteurs de la base roulante de Cérès 2.0 quand même >_< mais ils envoient du lourd quoi !!!

**Comment by astralien3000** [comment]
Surtout que je vais peut être ajouter un rapport d'engrenage qui va multiplier la vitesse par 2 (vu qu'on est large niveau couple) ! XD

**Comment by astralien3000** [comment]
Pour les archives, après avoir rapidement vérifié la faisabilité mécanique de la base roulante, j'ai acheté le materiel suivant : 
 - [nouveaux moteurs](http://www.francerobotique.com/moteurs-classiques/567-moteur-m%C3%A9tal-plan%C3%A9taire-premium-hd-12v-612rpm-avec-encodeur.html)
 - [encodeurs (les même que Céres 1 et 2.0)](http://www.robotshop.com/eu/fr/encodeur-rotatif-6mm-1024-p-r.html)
 - [poulie D20mm](http://www.conrad.fr/ce/fr/product/209513/Poulie-dentee-Reely-aluminium-percage-4-mm-Diametre-20-mm-Nombre-de-dents-20/SHOP_AREA_32457)
 - [poulie D38mm](http://www.conrad.fr/ce/fr/product/209516/Poulie-dentee-Reely-aluminium-percage-6-mm-Diametre-38-mm-Nombre-de-dents-40/SHOP_AREA_32457)
 - [courroie qui va bien (j'espère)](http://www.conrad.fr/ce/fr/product/209519/MODELCRAFT-Courroie-dentee-160-mm-64/SHOP_AREA_32457)

Pour le reste, je vais vampiriser Céres 1.1.

ps: C'était Noël à la poste ce matin !

**Comment by astralien3000** [comment]
Done !
Une méca au poil !
