### ISSUE TITLE
Commande driver moteurs (VNH2SP30)

### ISSUE THREAD

**Issue by astralien3000** [xenomorphales/xenomorphales#73]
On s'est donc arrêté sur [cette board](https://www.pololu.com/product/708).

Ça pique bien, le prix, quand même ><
Mais au moins, si elle tient sa promesse, on devrait pas avoir besoin d'en changer avant un bon bout de temps.

Pour le coups j'hésite un peu à en acheter 2 d'un coup...
Peut être 1 à la fois c'est mieux.

**Comment by Elioty** [comment]
J'aimerai bien avoir une Hermes 2 de mon côté pour travailler dessus (puis ça nous en fera deux de montée, en cas de besoin, hop, changement rapide) mais je n'aurais pas de moteur et encore moins le robot pour jouer avec les ponts en H donc tu peux en commander une ou deux dans un premier temps, c'est toi qui voit.

**Comment by astralien3000** [comment]
J'en ai commandé 2 finalement. Let's see.

**Comment by astralien3000** [comment]
Cartes (enfin) reçues, on est bon !
